Hw06 email
GoDmitrAn/nodejs-homework-rest-api pull request #5
Opened 2023-02-23 15:22 UTC by GoDmitrAn

homework to check

2023-02-23 18:47 UTC, Eastvarga requested changes
Є зауваження.

2023-02-23 18:47 UTC, Eastvarga commented on controllers/auth/signup.js
> +      html: `<h1> Hello there! <a href="/users/verify/${verificationToken}"> verify</a> </h1>`,
У пошті повинна бути повна лінка на ваш сервер - ніяких відносних
Додайте хост сервера

2023-02-23 18:47 UTC, Eastvarga commented on controllers/auth/verify.js
> +    if (user === undefined) {
таке собі рішення, якщо важливе саме існування юзера, тоді чому не використовуєте привод типу до буля !user?
Чи Вам вкрай важливо щоб юзер був саме невизначений, а якщо null то помилку кидати не требо?

2023-02-23 18:47 UTC, Eastvarga commented on controllers/auth/verify.js
> +      html: `<h1> Hello there! <a href="/users/verify/${storedUser.verificationToken}"> verify</a> </h1>`,
повний шлях повинен бути

2023-02-23 18:47 UTC, Eastvarga commented on controllers/auth/verify.js
> +    console.log(response);
консолі не потрібні в працюючому коді

2023-02-23 18:47 UTC, Eastvarga commented on schemas/users.js
> +  verify: Joi.string(),
чому не буль? Будьте Уважні коли читаєте  завдання

2023-02-23 20:02 UTC, GoDmitrAn commented on controllers/auth/signup.js
> +      html: `<h1> Hello there! <a href="/users/verify/${verificationToken}"> verify</a> </h1>`,
виправив

2023-02-23 20:04 UTC, GoDmitrAn commented on controllers/auth/verify.js
> +    if (user === undefined) {
метод файнд повертає юзера або андефайнд, виправив на !user

2023-02-23 20:04 UTC, GoDmitrAn commented on controllers/auth/verify.js
> +      html: `<h1> Hello there! <a href="/users/verify/${storedUser.verificationToken}"> verify</a> </h1>`,
виправив

2023-02-23 20:04 UTC, GoDmitrAn commented on controllers/auth/verify.js
> +    console.log(response);
виправив

2023-02-23 20:06 UTC, GoDmitrAn commented on schemas/users.js
> +  verify: Joi.string(),
згоден , неуважно читав, але в коді використовував як буль

2023-02-25 08:19 UTC, Eastvarga approved these changes

2023-02-25 08:20 UTC, merged